<?php

/**
 * RoyalMailShipping by StreamMarket
 *
 * @category    StreamMarket
 * @package StreamMarket_RoyalMailShipping
 * @author  Product Development Team <support@StreamMarket.co.uk>
 * @license http://extensions.StreamMarket.co.uk/license
 *
 */

namespace StreamMarket\RoyalMailShipping\Model\Config\Source;

class ServiceOffering implements \Magento\Framework\Data\OptionSourceInterface
{

    public function toOptionArray()
    {
		return [
				['value' => 'BF1', 'label' => 'HM Forces Mail'],
				['value' => 'BF2', 'label' => 'HM Forces Signed For'],
				['value' => 'BF7', 'label' => 'HM Forces Special Delivery (£500)'],
				['value' => 'BF8', 'label' => 'HM Forces Special Delivery (£1000)'],
				['value' => 'BF9', 'label' => 'HM Forces Special Delivery (£2500)'],
				['value' => 'BG1', 'label' => 'International Business Personal Correspondence Max Sort Residue (LL)'],
				['value' => 'BG2', 'label' => 'International Business Mail (LL) Max Sort Residue Standard'],
				['value' => 'BG3', 'label' => 'International Business Mail (LL) Max Sort Residue Economy'],
				['value' => 'BP1', 'label' => 'International Business Personal Correspondence Max Sort Residue (L)'],
				['value' => 'BP2', 'label' => 'International Business Mail (L) Max Sort Residue Standard'],
				['value' => 'BP3', 'label' => 'International Business Mail (L) Max Sort Residue Economy'],
				['value' => 'BPI', 'label' => 'International Business Printed Matter Packet'],
				['value' => 'BPL1', 'label' => 'Royal Mail 1st Class'],
				['value' => 'BPL2', 'label' => 'Royal Mail 2nd Class'],
				['value' => 'BPR1', 'label' => 'Royal Mail 1st Class Signed For'],
				['value' => 'BPR2', 'label' => 'Royal Mail 2nd Class Signed For'],
				['value' => 'CRL1', 'label' => 'Royal Mail 24 Standard/Signed For (Parcel - Daily Rate Service)'],
				['value' => 'CRL2', 'label' => 'Royal Mail 48 Standard/Signed For (Parcel - Daily Rate Service)'],
				['value' => 'DE1', 'label' => 'International Business Parcels Zero Sort High Vol Priority'],
				['value' => 'DE4', 'label' => 'International Business Parcels Zero Sort Priority'],
				['value' => 'DE6', 'label' => 'International Business Parcels Zero Sort Priority'],
				['value' => 'DEA', 'label' => 'DE Import Standard 24 Parcel'],
				['value' => 'DEB', 'label' => 'DE Import Standard 24 Parcel'],
				['value' => 'DEC', 'label' => 'DE Import Standard 24 (LL)'],
				['value' => 'DED', 'label' => 'DE Import Standard 48 (LL)'],
				['value' => 'DEE', 'label' => 'DE Import to EU Tracked & Signed (LL)'],
				['value' => 'DEG', 'label' => 'DE Import to EU Max Sort (LL)'],
				['value' => 'DEI', 'label' => 'DE Import to EU Tracked Parcel'],
				['value' => 'DEJ', 'label' => 'DE Import to EU Tracked & Signed Parcel'],
				['value' => 'DEK', 'label' => 'DE Import to EU Tracked High Vol (LL)'],
				['value' => 'DEM', 'label' => 'DE Import to EU Max Sort Parcel'],
				['value' => 'DG1', 'label' => 'International Business Mail (LL) Country Priced High Vol Priority'],
				['value' => 'DG3', 'label' => 'International Business Mail (LL) Country Priced High Vol Economy'],
				['value' => 'DG4', 'label' => 'International Business Mail (LL) Country Priced Priority'],
				['value' => 'DG6', 'label' => 'International Business Mail (LL) Country Priced Economy'],
				['value' => 'DP1', 'label' => 'International Business Mail (L) Country Sort High Vol Priority'],
				['value' => 'DP3', 'label' => 'International Business Personal Correspondence (L) Untracked'],
				['value' => 'DP4', 'label' => 'International Business Mail (L) Country Sort Priority'],
				['value' => 'DP6', 'label' => 'International Business Mail (LL) Country Sort Economy'],
				['value' => 'DW1', 'label' => 'International Business Parcels'],
				['value' => 'FS1', 'label' => 'Royal Mail 24 Standard/Signed For Large Letter (Flat Rate Service)'],
				['value' => 'FS2', 'label' => 'Royal Mail 48 Standard/Signed For Large Letter (Flat Rate Service)'],
				['value' => 'FS7', 'label' => 'Royal Mail 24 (Presorted) (LL)'],
				['value' => 'FS8', 'label' => 'Royal Mail 48 (Presorted) (LL)'],
				['value' => 'HVB', 'label' => 'International Tracked Parcels 0-30kg'],
				['value' => 'HVC', 'label' => 'International Tracked & Signed Parcels 0-30kg'],
				['value' => 'HVE', 'label' => 'International Tracked Parcels 0-30kg Extra Comp'],
				['value' => 'HVF', 'label' => 'International Tracked & Signed Parcels 0-30kg Extra Comp'],
				['value' => 'IE1', 'label' => 'International Business Parcels Zone Sort Priority Service'],
				['value' => 'IE3', 'label' => 'International Business Parcels Zone Sort Economy Service'],
				['value' => 'IG1', 'label' => 'International Business Mail Large Letter Zone Sort Priority'],
				['value' => 'IG3', 'label' => 'International Business Mail Large Letter Zone Sort Economy'],
				['value' => 'IG4', 'label' => 'International Business Mail Large Letter Zone Sort Priority Machine'],
				['value' => 'IG6', 'label' => 'International Business Mail Large Letter Zone Sort Economy Machine'],
				['value' => 'IP1', 'label' => 'International Business Mail Letters Zone Sort Priority'],
				['value' => 'IP3', 'label' => 'International Business Mail Letters Zone Sort Economy'],
				['value' => 'IP4', 'label' => 'International Business Mail Letters Zone Sort Priority Machine'],
				['value' => 'IP6', 'label' => 'International Business Mail Letters Zone Sort Economy Machine'],
				['value' => 'ITA', 'label' => 'Import DE Tracked Returns 24'],
				['value' => 'ITB', 'label' => 'Import DE Tracked Returns 48'],
				['value' => 'ITC', 'label' => 'Import DE Tracked 24 Letter-boxable High Volume'],
				['value' => 'ITD', 'label' => 'Import DE Tracked 48 Letter-boxable High Volume'],
				['value' => 'ITE', 'label' => 'Import DE Tracked 48 Letter-boxable'],
				['value' => 'ITF', 'label' => 'Import DE Tracked 24 Letter-boxable'],
				['value' => 'ITL', 'label' => 'Import DE Tracked 48 High Volume'],
				['value' => 'ITM', 'label' => 'Import DE Tracked 24 High Volume'],
				['value' => 'ITN', 'label' => 'Import DE Tracked 24'],
				['value' => 'ITR', 'label' => 'DE Import to EU Signed Parcel'],
				['value' => 'ITS', 'label' => 'Import DE Tracked 48'],
				['value' => 'MB1', 'label' => 'International Business Parcels Print Direct Priority'],
				['value' => 'MB2', 'label' => 'International Business Parcels Print Direct Standard'],
				['value' => 'MB3', 'label' => 'International Business Parcels Print Direct Economy'],
				['value' => 'MP0', 'label' => 'International Business Parcels Signed Extra Compensation Country Priced'],
				['value' => 'MP1', 'label' => 'International Business Parcels Tracked Zone Sort'],
				['value' => 'MP4', 'label' => 'International Business Parcels Tracked Extra Comp Zone Sort'],
				['value' => 'MP5', 'label' => 'International Business Parcels Signed  Zone Sort'],
				['value' => 'MP6', 'label' => 'International Business Parcels Signed Extra Compensation  Zone Sort'],
				['value' => 'MP7', 'label' => 'International Business Parcels Tracked Country Priced'],
				['value' => 'MP8', 'label' => 'International Business Parcels Tracked Extra Comp Country Priced'],
				['value' => 'MP9', 'label' => 'International Business Parcels Signed Country Priced'],
				['value' => 'MPL', 'label' => 'International Business Mail Tracked High Vol. Country Priced'],
				['value' => 'MPM', 'label' => 'International Business Mail Tracked & Signed High Vol. Country Priced'],
				['value' => 'MPN', 'label' => 'International Business Mail Signed High Vol. Country Priced'],
				['value' => 'MPO', 'label' => 'International Business Mail Tracked High Vol. Extra Comp Country Priced'],
				['value' => 'MPP', 'label' => 'International Business Mail Tracked & Signed High Vol. Extra Comp Country Priced'],
				['value' => 'MPR', 'label' => 'International Business Parcel Tracked Boxable Country Priced'],
				['value' => 'MTA', 'label' => 'International Business Parcels Tracked & Signed Zone Sort'],
				['value' => 'MTB', 'label' => 'International Business Parcels Tracked & Signed Extra Compensation Zone Sort'],
				['value' => 'MTC', 'label' => 'International Business Mail Tracked & Signed Zone Sort'],
				['value' => 'MTD', 'label' => 'International Business Mail Tracked & Signed Extra Compensation Zone Sort'],
				['value' => 'MTE', 'label' => 'International Business Parcels Tracked & Signed Country Priced'],
				['value' => 'MTF', 'label' => 'International Business Parcels Tracked & Signed Extra Compensation Country Priced'],
				['value' => 'MTG', 'label' => 'International Business Mail Tracked & Signed Country Priced'],
				['value' => 'MTI', 'label' => 'International Business Mail Tracked Zone Sort'],
				['value' => 'MTJ', 'label' => 'International Business Mail Tracked Extra Comp Zone Sort'],
				['value' => 'MTK', 'label' => 'International Business Mail Tracked Country Priced'],
				['value' => 'MTM', 'label' => 'International Business Mail Signed Zone Sort'],
				['value' => 'MTN', 'label' => 'International Business Mail Signed Extra Compensation Zone Sort'],
				['value' => 'MTO', 'label' => 'International Business Mail Signed Country Priced'],
				['value' => 'MTP', 'label' => 'International Business Mail Signed Extra Compensation Country Priced'],
				['value' => 'MTS', 'label' => 'International Business Parcels Tracked Direct Ireland Country'],
				['value' => 'OLA', 'label' => 'International Standard On Account'],
				['value' => 'OLS', 'label' => 'International Economy On Account'],
				['value' => 'OSA', 'label' => 'International Signed On Account'],
				['value' => 'OSB', 'label' => 'International Signed On Account Extra Comp'],
				['value' => 'OTA', 'label' => 'International Tracked On Account'],
				['value' => 'OTB', 'label' => 'International Tracked On Account Extra Comp'],
				['value' => 'OTC', 'label' => 'International Tracked & Signed On Account'],
				['value' => 'OTD', 'label' => 'International Tracked & Signed On Account Extra Comp'],
				['value' => 'OZ1', 'label' => 'International Business Mail Mixed Zone Sort Priority'],
				['value' => 'OZ3', 'label' => 'International Business Mail Mixed Zone Sort Economy'],
				['value' => 'OZ4', 'label' => 'International Business Mail Mixed Zone Sort Priority Machine'],
				['value' => 'OZ6', 'label' => 'International Business Mail Mixed Zone Sort Economy Machine'],
				['value' => 'PK0', 'label' => 'Royal Mail 48 (LL) Flat Rate'],
				['value' => 'PK1', 'label' => 'Royal Mail 24 Standard/Signed For (Parcel - Sort8 - Flat Rate Service)'],
				['value' => 'PK2', 'label' => 'Royal Mail 48 Standard/Signed For (Parcel - Sort8 - Flat Rate Service)'],
				['value' => 'PK3', 'label' => 'Royal Mail 24 Standard/Signed For (Parcel - Sort8 - Daily Rate Service)'],
				['value' => 'PK4', 'label' => 'Royal Mail 48 Standard/Signed For (Parcel - Sort8 - Daily Rate Service)'],
				['value' => 'PK7', 'label' => 'Royal Mail 24 (Presorted) (P)'],
				['value' => 'PK8', 'label' => 'Royal Mail 48 (Presorted) (P)'],
				['value' => 'PK9', 'label' => 'Royal Mail 24 (LL) Flat Rate'],
				['value' => 'PKB', 'label' => 'RM24 (Presorted) (P) Annual Flat Rate'],
				['value' => 'PKD', 'label' => 'RM48 (Presorted) (P) Annual Flat Rate'],
				['value' => 'PKK', 'label' => 'RM48 (Presorted) (LL) Annual Flat Rate'],
				['value' => 'PKM', 'label' => 'RM24 (Presorted) (LL) Annual Flat Rate'],
				['value' => 'PPF1', 'label' => 'Royal Mail 24 Standard/Signed For (Packetpost- Flat Rate Service)'],
				['value' => 'PPF2', 'label' => 'Royal Mail 48 Standard/Signed For (Packetpost- Flat Rate Service)'],
				['value' => 'PPJ1', 'label' => 'Parcelpost Flat Rate (Annual)'],
				['value' => 'PPJ2', 'label' => 'Parcelpost Flat Rate (Annual)'],
				['value' => 'PPS', 'label' => 'RM24 (LL) Annual Flat Rate'],
				['value' => 'PPT', 'label' => 'RM48 (LL) Annual Flat Rate'],
				['value' => 'PS5', 'label' => 'International Business Personal Correspondence Max Sort (L)'],
				['value' => 'PS7', 'label' => 'International Business Mail Large Letter Max Sort Priority Service'],
				['value' => 'PS8', 'label' => 'International Business Mail Large Letter Max Sort Economy Service'],
				['value' => 'PSA', 'label' => 'International Business Mail Letters Max Sort Standard'],
				['value' => 'PSB', 'label' => 'International Business Mail Large Letter Max Sort Standard Service'],
				['value' => 'RM0', 'label' => 'Royal Mail 48 (Sort8)(P) Annual Flat Rate'],
				['value' => 'RM1', 'label' => 'Royal Mail 24 (LL) Daily Rate'],
				['value' => 'RM2', 'label' => 'Royal Mail 24 (P) Daily Rate'],
				['value' => 'RM3', 'label' => 'Royal Mail 48 (LL) Daily Rate'],
				['value' => 'RM4', 'label' => 'Royal Mail 48 (P) Daily Rate'],
				['value' => 'RM5', 'label' => 'Royal Mail 24 (P) Flat Rate'],
				['value' => 'RM6', 'label' => 'Royal Mail 48 (P) Flat Rate'],
				['value' => 'RM7', 'label' => 'Royal Mail 24 (SORT8) (LL) Annual Flat Rate'],
				['value' => 'RM8', 'label' => 'Royal Mail 24 (SORT8) (P) Annual Flat Rate'],
				['value' => 'RM9', 'label' => 'Royal Mail 48 (SORT8) (LL) Annual Flat Rate'],
				['value' => 'SD1', 'label' => 'Special Delivery Guaranteed By 1PM (£750)'],
				['value' => 'SD2', 'label' => 'Special Delivery Guaranteed By 1PM (£1000)'],
				['value' => 'SD3', 'label' => 'Special Delivery Guaranteed By 1PM (£2500)'],
				['value' => 'SD4', 'label' => 'Special Delivery Guaranteed By 9AM (£750)'],
				['value' => 'SD5', 'label' => 'Special Delivery Guaranteed By 9AM (£1000)'],
				['value' => 'SD6', 'label' => 'Special Delivery Guaranteed By 9AM (£2500)'],
				['value' => 'SDA', 'label' => 'Special Delivery Guaranteed By 1PM (ID) (£750)'],
				['value' => 'SDB', 'label' => 'Special Delivery Guaranteed By 1PM (ID) (£1000)'],
				['value' => 'SDC', 'label' => 'Special Delivery Guaranteed By 1PM (ID) (£2500)'],
				['value' => 'SDE', 'label' => 'Special Delivery Guaranteed By 9AM (ID) (£750)'],
				['value' => 'SDF', 'label' => 'Special Delivery Guaranteed By 9AM (ID) (£1000)'],
				['value' => 'SDG', 'label' => 'Special Delivery Guaranteed By 9AM (ID) (£2500)'],
				['value' => 'SDH', 'label' => 'Special Delivery Guaranteed By 1PM (AGE) (£750)'],
				['value' => 'SDJ', 'label' => 'Special Delivery Guaranteed By 1PM (AGE) (£1000)'],
				['value' => 'SDK', 'label' => 'Special Delivery Guaranteed By 1PM (AGE) (£2500)'],
				['value' => 'SDM', 'label' => 'Special Delivery Guaranteed By 9AM (AGE) (£750)'],
				['value' => 'SDN', 'label' => 'Special Delivery Guaranteed By 9AM (AGE) (£1000)'],
				['value' => 'SDQ', 'label' => 'Special Delivery Guaranteed By 9AM (AGE) (£2500)'],
				['value' => 'SDV', 'label' => 'Special Delivery Guaranteed (AGE) (£750)'],
				['value' => 'SDW', 'label' => 'Special Delivery Guaranteed (AGE) (£1000)'],
				['value' => 'SDX', 'label' => 'Special Delivery Guaranteed (AGE) (£2500)'],
				['value' => 'SDY', 'label' => 'Special Delivery Guaranteed (ID) (£750)'],
				['value' => 'SDZ', 'label' => 'Special Delivery Guaranteed (ID) (£1000)'],
				['value' => 'SEA', 'label' => 'Special Delivery Guaranteed (ID) (£2500)'],
				['value' => 'SEB', 'label' => 'Special Delivery Guaranteed (£750)'],
				['value' => 'SEC', 'label' => 'Special Delivery Guaranteed (£1000)'],
				['value' => 'SED', 'label' => 'Special Delivery Guaranteed (£2500)'],
				['value' => 'STL1', 'label' => 'Royal Mail 1st Class Standard/Signed For (Letters - Daily Rate service)'],
				['value' => 'STL2', 'label' => 'Royal Mail 2nd Class Standard/Signed For (Letters - Daily Rate service)'],
				['value' => 'TPA', 'label' => 'Tracked 24 High Volume Signature (AGE)'],
				['value' => 'TPB', 'label' => 'Tracked 48 High Volume Signature (AGE)'],
				['value' => 'TPC', 'label' => 'Tracked 24 Signature (AGE)'],
				['value' => 'TPD', 'label' => 'Tracked 48 Signature (AGE)'],
				['value' => 'TPL', 'label' => 'Tracked 48 High Volume Signature / No Signature'],
				['value' => 'TPM', 'label' => 'Tracked 24 High Volume Signature / No Signature'],
				['value' => 'TPN', 'label' => 'Tracked 24 Signature / No Signature'],
				['value' => 'TPS', 'label' => 'Tracked 48 Signature / No Signature'],
				['value' => 'TRL', 'label' => 'Tracked Letter-Boxable 48 High Volume Signature / No Signature'],
				['value' => 'TRM', 'label' => 'Tracked Letter-Boxable 24 High Volume Signature / No Signature'],
				['value' => 'TRN', 'label' => 'Tracked Letter-Boxable 24 Signature / No Signature'],
				['value' => 'TRS', 'label' => 'Tracked Letter-Boxable 48 Signature / No Signature'],
				['value' => 'TSN', 'label' => 'Tracked Returns 24'],
				['value' => 'TSS', 'label' => 'Tracked Returns 48'],
				['value' => 'WE1', 'label' => 'International Business Parcels Zero Sort Priority'],
				['value' => 'WE3', 'label' => 'International Business Parcels Zero Sort Economy'],
				['value' => 'WG1', 'label' => 'International Business Mail Large Letter Zero Sort Priority'],
				['value' => 'WG3', 'label' => 'International Business Mail Large Letter Zero Sort Economy'],
				['value' => 'WG4', 'label' => 'International Business Mail Large Letter Zero Sort Priority Machine'],
				['value' => 'WG6', 'label' => 'International Business Mail Large Letter Zero Sort Economy Machine'],
				['value' => 'WP1', 'label' => 'International Business Mail Letters Zero Sort Priority'],
				['value' => 'WP3', 'label' => 'International Business Mail Letters Zero Sort Economy'],
				['value' => 'WP4', 'label' => 'International Business Mail Letters Zero Sort Priority Machine'],
				['value' => 'WW1', 'label' => 'International Business Mail Mixed Zero Sort Priority'],
				['value' => 'WW3', 'label' => 'International Business Mail Mixed Zero Sort Economy'],
				['value' => 'WW4', 'label' => 'International Business Mail Mixed Zero Sort Priority Machine'],
				['value' => 'Y64', 'label' => 'Relay Next Day Mail A2'],
				['value' => 'Y65', 'label' => 'Relay Next Day Mail A3'],
				['value' => 'Y66', 'label' => 'Relay Next Day Sack'],
				['value' => 'Y67', 'label' => 'Relay Next Day Tote'],
				['value' => 'Y68', 'label' => 'Relay Next Day Retail'],
				['value' => 'Y69', 'label' => 'Relay Next Day Tube'],
				['value' => 'Y70', 'label' => 'Relay Next Day Clearings'],
				['value' => 'Y71', 'label' => 'Relay Next Day Archives'],
				['value' => 'Y72', 'label' => 'Relay Next Day Parcel'],
				['value' => 'Y73', 'label' => 'Relay Next Day Special Returns'],
				['value' => 'Y74', 'label' => 'Relay Next Day Parts'],
				['value' => 'Y75', 'label' => 'Relay Next Day Fragile'],
				['value' => 'Y76', 'label' => 'Relay Next Day Mail'],
				['value' => 'Y77', 'label' => 'Relay Next Day Stationary'],
				['value' => 'Y78', 'label' => 'Relay Next Day Returns'],
				['value' => 'Y79', 'label' => 'Relay Next Day Uniform'],
				['value' => 'Y80', 'label' => 'Relay Next Day Sensitive Waste (SDS)'],
				['value' => 'Y81', 'label' => 'Relay Next Day Enhanced 500'],
				['value' => 'Y82', 'label' => 'Relay Next Day Enhanced 1000'],
				['value' => 'Y83', 'label' => 'Relay Next Day Enhanced 1500'],
				['value' => 'Y84', 'label' => 'Relay Next Day Enhanced 2000'],
				['value' => 'Y85', 'label' => 'Relay Next Day Enhanced 2500'],
				['value' => 'Y86', 'label' => 'Relay Next Day Enhanced 3000'],
				['value' => 'Y87', 'label' => 'Relay Next Day Box'],
				['value' => 'Y88', 'label' => 'Relay Next Day Recycle'],
				['value' => 'Y89', 'label' => 'Relay Next Day Pallet'],
				['value' => 'Y90', 'label' => 'Relay Next Day Loose'],
				['value' => 'Y91', 'label' => 'Relay Next Day Pouch'],
				['value' => 'Y92', 'label' => 'Relay Next Day Holdall'],
				['value' => 'Y93', 'label' => 'Relay Next Day Clearings Pouch'],
				['value' => 'Y94', 'label' => 'Relay Next Day HO Mail Pouch'],
				['value' => 'Y95', 'label' => 'Relay Next Day Returns Pouch'],
				['value' => 'Y96', 'label' => 'Relay Next Day Archive Pouch'],
				['value' => 'Y97', 'label' => 'Relay Next Day Critical Run Pouch'],
				['value' => 'Y98', 'label' => 'Relay Next Day Smart Meter Tote'],
				['value' => 'Y99', 'label' => 'Relay Next Day Mail A4']
				];
	}
}
