<?php
//echo BP;
$admin_path = $this->helper('Magento\Backend\Helper\Data')->getAreaFrontName();
$serviceMatricJson = $this->getSrviceMatrixJson();
$helper = $this->helper('StreamMarket\RoyalMailShipping\Helper\CurlRequest');
$package_width = $helper->getSystemConfigValue('carriers/smroyalmail/smroyalmail_item/package_width');
$package_height = $helper->getSystemConfigValue('carriers/smroyalmail/smroyalmail_item/package_height');
$package_length = $helper->getSystemConfigValue('carriers/smroyalmail/smroyalmail_item/package_length');
$package_type = $helper->getSystemConfigValue('carriers/smroyalmail/smroyalmail_item/package_type');
$merge_label = $helper->getSystemConfigValue('carriers/smroyalmail/smroyalmail_item/merge_label');

$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('StreamMarket\RoyalMailShipping\Block\Tracking');
$allow_methods = \Magento\Framework\App\ObjectManager::getInstance()->get('StreamMarket\RoyalMailShipping\Block\Adminhtml\Mass\Order\Ship');
$serviceMatricJson = $allow_methods->getSrviceMatrixJson();

$result = json_decode($serviceMatricJson, true);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$service_off_data = $objectManager->get('StreamMarket\RoyalMailShipping\Model\Config\Source\ServiceOffering');
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('carriers/smroyalmail/allowed_methods');
$data = $service_off_data->toOptionArray();


$store_allowed = explode(',',$conf);
foreach($data as $dataVal){
	foreach($store_allowed as $val){
		if($val == $dataVal['value']){
	    $allowed_methods[] = array('value' => $dataVal['value'],'label' => $dataVal['label']);
		}
	}
}

$parceltype = \Magento\Framework\App\ObjectManager::getInstance()->get('StreamMarket\RoyalMailShipping\Model\Config\Source\ParcelType');
$parceltype_data = $parceltype->toOptionArray();

$shipmentId = $this->getShipment()->getId();
$ship_data = $this->getShipment()->getData();
$orderId = $ship_data['order_id'];
$shipmment = $myBlock->getTracking($shipmentId);
$tracksCollection = $shipmment->getTracksCollection();
$base_url = $helper->getBaseUrl();
$admin_url_prepare = $base_url.$admin_path;

 ?>
<div class="track-ctr">
<?php
foreach ($tracksCollection->getItems() as $track) {
     $trackNumbers = $track->getTrackNumber();
	 $pdf_path = $helper->getTrackingInfo($trackNumbers,$shipmentId,0);
	 $cn23_merge_data = $helper->getTrackingInfo($trackNumbers,$shipmentId,2);
	 if($trackNumbers){ ?>
	 	 <?php if($merge_label == 1 ){
				$cn23_path = $helper->getTrackingInfo($trackNumbers,$shipmentId,2);
		 }else{
			 $cn23_path = $helper->getTrackingInfo($trackNumbers,$shipmentId,1);
		 } ?>
		 <?php if(!$cn23_merge_data){ ?>
		 <div class="print-lbl"><a href="<?php echo $base_url; ?>media<?php echo $pdf_path; ?>" target="_blank">Print Shipping Label</a></div>
		 <?php } ?>
		 <?php if($cn23_path){ ?>
		 <div class="print-lbl"><a href="<?php echo $base_url; ?>media<?php echo $cn23_path; ?>" target="_blank">Print CN23 Label</a></div>
<?php  } } } ?>
</div>
<?php if ($btnHtml = $this->getData('button_html')): ?>
    <div id="custom-print-label-button" style="text-align: center; margin: 10px 0; display: none">
        <?php echo $btnHtml ?>
    </div>
    <script>
        require(['jquery'], function (jQuery) {
            if (jQuery('.action-create-label').length == 0) {
                jQuery('#custom-print-label-button').show();
            }
        });
    </script>
    <?php
endif;
if (($transaction = $this->getTransaction()) && $transaction->getId()):
    ?>
    <div style="text-align: center; margin: 10px 0;">
        <button class="action-default scalable" onclick="setLocation('<?php
        echo $this->getUrl('smroyalmail/transaction/generateLabel',
                array('transaction_id' => $transaction->getId()))
        ?>')" type="button" title="<?php echo __('Generate Label') ?>">
            <span><?php echo __('Generate Label') ?></span>
        </button>
    </div>
<?php endif; ?>
<?php
$order = $helper->getOrderDetails($orderId);
 $currency_code = $order->getOrderCurrencyCode();
 $item_details = $this->getShipment()->getAllItems();
 $total_weight = 0;
 $total_price = 0;
 foreach ($item_details as $item) {
 $_orderItem = $this->getShipment()->getOrder()->getItemById($item->getOrderItemId());
 if ($item->getIsVirtual() || ($_orderItem->isShipSeparately() && !($_orderItem->getParentItemId() || $_orderItem->getParentItem())) || (!$_orderItem->isShipSeparately() && ($_orderItem->getParentItemId() || $_orderItem->getParentItem()))):
 continue;
 endif;
 
 $qty_ordered = $item->getQty();
 $price = $item->getPrice();
 $weight = $item->getWeight();
 $total_weight += ($weight * $qty_ordered);
 $total_price += ($price * $qty_ordered);
 }

$shippingAddress = $order->getShippingAddress()->getData();

$country_id = $shippingAddress['country_id'];
$postcode = $shippingAddress['postcode'];

$city = $shippingAddress['city'];	 
$service_offering = $helper->getAvailbiltyRequest();
if(isset($service_offering['error'])){
	echo "<p class='error-msg'>".$service_offering['error']."</p>";
}

/* @var $royalMailCarrier \StreamMarket\RoyalMailShipping\Model\Carrier */
$royalMailCarrier = $this->getRoyalMailCarrier();
if (!$this->getShipment()->getAllTracks() && $royalMailCarrier) {
    $carrier = $this->getShipment()->getOrder()->getShippingCarrier();
    $allowedMethods = $royalMailCarrier->getAllowedMethods();
    $serviceTypes = $royalMailCarrier->getAllowedServiceTypes(true);
    $serviceTypesCount = count($serviceTypes);
    $serviceMatric = $royalMailCarrier->getServiceMatrix()->getServiceOfferingsByServiceTypes(array_keys($serviceTypes),
    array_keys($allowedMethods));
    $serviceMatricJson = json_encode($serviceMatric);
	array_unshift($serviceTypes,
            array('value' => '', 'label' => __('--Please Select--')));
    
        $action = $this->getUrl('smroyalmail/shipment/shipWithRoyalmail',
                array('shipment_id' => $this->getShipment()->getId()));
				if(!array_key_exists("error",$service_offering)){
        ?>
        <div class="admin__collapsible-block-wrapper sm_royalmail" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
            <div data-role="collapsible">
                <div data-role="trigger" class="admin__collapsible-title">
                    <span class="admin__page-section-title"><?php
                        if ($carrier && $carrier->getCarrierCode() == 'smroyalmail') {
                            echo __('Or choose different service and ');
                        }
                        ?> <?php echo __('Ship with') ?> <?php echo $royalMailCarrier->getCarrierTitle() ?></span>
                </div>
            </div>
            <div data-role="content">
                <div class="entry-edit form-inline">
                        <div class="fieldset-wrapper">
                            <div class="admin__fieldset-wrapper-content">
                                <fieldset class="admin__fieldset">
                                    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>

                                    <!--<div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Service Type') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <select id="service_type" name="service_type" data-validate='{"required":true}' class="admin__control-select" >
                                                <?php foreach ($serviceTypes as $k => $v): ?>
                                                    <option value="<?php echo $v['value'] ?>"><?php echo $v['label'] ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>-->
                                    <div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Service Offering') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <select id="delivery_type_code" name="service_offering" data-validate='{"required":true}' class="admin__control-select">
                                             <option value=""><?php echo __('--Please Select--') ?></option>
												<?php foreach($allowed_methods as $data): ?>
												<option value="<?= $data['value']; ?>"><?= $data['label']; ?></option>
												<?php endforeach; ?>
											</select>
                                        </div>
                                    </div>
									<div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Parcel Type') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <select id="parcel_type" name="parcel_type" data-validate='{"required":true}' class="admin__control-select">
                                                <option value=""><?php echo __('--Please Select--') ?></option>
                                            </select>
                                        </div>
                                    </div>
									<input type="hidden" class="input-text admin__control-text" id="package_weight" value="<?php if($total_weight){ echo $total_weight; }?>" />
									<!--<div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Package Weight') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <input type="number" class="input-text admin__control-text" id="package_weight" value="<?php if($total_weight){ echo $total_weight; }?>" />
                                        </div>
                                    </div>-->
									<div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Package Width') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <input type="number" class="input-text admin__control-text" id="package_width" value="<?php if($package_width){ echo $package_width; }?>" />
                                        </div>
                                    </div>
									<div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Package Length') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <input type="number" class="input-text admin__control-text" id="package_length" value="<?php if($package_length){ echo $package_length; }?>" />
                                        </div>
                                    </div>
									<div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Package Height') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <input type="number" class="input-text admin__control-text" id="package_height" value="<?php if($package_height){ echo $package_height; }?>" />
                                        </div>
                                    </div>
									<div class="admin__field _required">
                                        <label class="admin__field-label">
                                            <span><?php echo __('Product Type') ?></span>
                                        </label>
                                        <div class="admin__field-control">
                                            <select id="product_type" name="service_offering" data-validate='{"required":true}' class="admin__control-select">
                                                <option value="NDX" <?php if($package_type == 'NDX') { echo "selected"; } ?>>Non-Documents</option>
												<option value="DOX" <?php if($package_type == 'DOX') { echo "selected"; } ?>>Documents</option>
										    </select>
                                        </div>
                                    </div>
									<div class="admin__field">
										<label class="admin__field-label">
											<span><?php echo __('Signed For') ?></span>
										</label>
										<div class="admin__field-control">
											<select id="signed_for" name="signed_for" class="admin__control-select">
												<option value="0"><?php echo __('No') ?></option>
												<option value="1"><?php echo __('Yes') ?></option>
											</select>
										</div>
									</div>
                                    <div class="admin__field">
                                        <label class="admin__field-label"></label>
                                        <div class="admin__field-control">
                                            <input type="hidden" name="hideit" id="hideit" value="" />
                                            <button type="submit" title="Submit" id="proceed-btn" class="action submit primary">
                                                <span><?php echo __('Proceed') ?></span>
                                            </button>
                                        </div>
										<div class="ajax_loader" style="display:none">
									<img id="ajax_loader" src="<?php echo $this->getViewFileUrl('StreamMarket_RoyalMailShipping::images/ajax-loader.gif'); ?>" />
									<?php echo __('Processing ...') ?></div>
                                    </div>
									<input type="hidden" id="shipping_id" value="<?php echo $this->getShipment()->getId(); ?>" />
									
                                </fieldset>
                            </div>
                        </div>
					
                  </div>
            </div>
            <script>
                require(["jquery"],function($) {
					var container_url = "<?php echo $this->getUrl('smroyalmail/shipment/GetContainerType'); ?>";
						$('#delivery_type_code').change(function () {
						var val = $(this).val();
						new Ajax.Request(container_url + 'code/' + val,
                                {
                                    method: "get",
                                    onSuccess: function (response) {
										$("#parcel_type").html(response.responseJSON.html);
                                    }
                                });
							});
							
					$("#proceed-btn").click(function () {
						var shipment_id = $('#shipping_id').val();
						var service_offering = $('#delivery_type_code').val();
						var product_type = $('#product_type').val();
						var package_width = $('#package_width').val();
						var package_length = $('#package_length').val();
						var package_height = $('#package_height').val();
						var package_weight = $('#package_weight').val();
						var parcel_type = $('#parcel_type').val();
						var signed_for = jQuery('#signed_for').val();
						
						if(service_offering == ''){
							alert("Please select service offering");
						return false;
						}
						if(package_width == ''){
							alert("Package width required");
						return false;
						}
						if(package_length == ''){
							alert("Package length required");
						return false;
						}
						if(package_height == ''){
							alert("Package height required");
						return false;
						}
						$('.ajax_loader').show();
			var customurl = "<?php echo $admin_url_prepare; ?>/smroyalmail/shipment/shipWithRoyalmail";
            $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                data: {
                    shipment_id: shipment_id,
					service_offering: service_offering,
					package_width: package_width,
					package_length: package_length,
					package_height: package_height,
					product_type:product_type,
					package_weight:package_weight,
					parcel_type:parcel_type,
					signed_for:signed_for
				},
				
            complete: function(response) {             
                $('.ajax_loader').hide();
				location.reload();
				},
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
       
    });
	});			
            </script>
        </div>
		
				<?php }
}
?>
<?php echo $this->getChildHtml('sm_calling_block'); ?>
<style type="text/css">
    .admin__collapsible-block-wrapper.sm_royalmail{border: 2px solid #cccccc; margin-top: 5px; padding: 5px;background-color: burlywood}
    .admin__page-section .sm_royalmail .admin__field > .admin__field-control{clear: none; float: left;}
    .admin__page-section .admin__page-section-content .sm_royalmail .admin__field > .admin__field-label{line-height: 3.2rem; text-align: right; width: calc( (100%) * 0.25 - 30px );}
    .admin__page-section .admin__page-section-content .sm_royalmail .admin__field._required > .admin__field-label > span::after{ left: auto; margin-left: 10px;}
	.ajax_loader {margin-left: 23px;float: left;}
	.print-lbl {background: #e3e3e3;width: 22%;text-align: center;line-height: 40px;margin: 0 auto;margin-bottom: 10px;}
	.print-lbl > a {color: #000;font-size: 15px;}
	button.action-create-label {display: none;}
	.error-msg {text-align: center;font-size: 14px;color: red;}
	button.action-default.scalable {display: none;}
</style>