<?php

/**
 * RoyalMailShipping by StreamMarket
 *
 * @category    StreamMarket
 * @package StreamMarket_RoyalMailShipping
 * @author  Product Development Team <support@StreamMarket.co.uk>
 * @license http://extensions.StreamMarket.co.uk/license
 *
 */

namespace StreamMarket\RoyalMailShipping\Model\Carrier;

/**
 * Royal Mail Shipping Codes
 */
class Codes
{

    private $_codes = [];

    /**
     * Codes constructor
     */
    public function __construct()
    {
        $this->_codes = array(
            'service_type' => array(//serviceType
                '1' => __('Royal Mail 24 / 1st Class'),
                '2' => __('Royal Mail 48 / 2nd Class'),
                'D' => __('Special Delivery Guaranteed'),
                'H' => __('HM Forces (BFPO)'),
                'I' => __('International'),
                'R' => __('Tracked Returns'),
                'T' => __('Royal Mail Tracked'),
            ),
            'method' => array(//serviceOffering

						'BF1' => __ ('HM Forces Mail'),
						'BF2' => __ ('HM Forces Signed For'),
						'BF7' => __ ('HM Forces Special Delivery (£500)'),
						'BF8' => __ ('HM Forces Special Delivery (£1000)'),
						'BF9' => __ ('HM Forces Special Delivery (£2500)'),
						'BG1' => __ ('International Business Personal Correspondence Max Sort Residue (LL)'),
						'BG2' => __ ('International Business Mail (LL) Max Sort Residue Standard'),
						'BG3' => __ ('International Business Mail (LL) Max Sort Residue Economy'),
						'BP1' => __ ('International Business Personal Correspondence Max Sort Residue (L)'),
						'BP2' => __ ('International Business Mail (L) Max Sort Residue Standard'),
						'BP3' => __ ('International Business Mail (L) Max Sort Residue Economy'),
						'BPI' => __ ('International Business Printed Matter Packet'),
						'BPL1' => __ ('Royal Mail 1st Class'),
						'BPL2' => __ ('Royal Mail 2nd Class'),
						'BPR1' => __ ('Royal Mail 1st Class Signed For'),
						'BPR2' => __ ('Royal Mail 2nd Class Signed For'),
						'CRL1' => __ ('Royal Mail 24 Standard/Signed For (Parcel - Daily Rate Service)'),
						'CRL2' => __ ('Royal Mail 48 Standard/Signed For (Parcel - Daily Rate Service)'),
						'DE1' => __ ('International Business Parcels Zero Sort High Vol Priority'),
						'DE4' => __ ('International Business Parcels Zero Sort Priority'),
						'DE6' => __ ('International Business Parcels Zero Sort Priority'),
						'DEA' => __ ('DE Import Standard 24 Parcel'),
						'DEB' => __ ('DE Import Standard 24 Parcel'),
						'DEC' => __ ('DE Import Standard 24 (LL)'),
						'DED' => __ ('DE Import Standard 48 (LL)'),
						'DEE' => __ ('DE Import to EU Tracked & Signed (LL)'),
						'DEG' => __ ('DE Import to EU Max Sort (LL)'),
						'DEI' => __ ('DE Import to EU Tracked Parcel'),
						'DEJ' => __ ('DE Import to EU Tracked & Signed Parcel'),
						'DEK' => __ ('DE Import to EU Tracked High Vol (LL)'),
						'DEM' => __ ('DE Import to EU Max Sort Parcel'),
						'DG1' => __ ('International Business Mail (LL) Country Priced High Vol Priority'),
						'DG3' => __ ('International Business Mail (LL) Country Priced High Vol Economy'),
						'DG4' => __ ('International Business Mail (LL) Country Priced Priority'),
						'DG6' => __ ('International Business Mail (LL) Country Priced Economy'),
						'DP1' => __ ('International Business Mail (L) Country Sort High Vol Priority'),
						'DP3' => __ ('International Business Personal Correspondence (L) Untracked'),
						'DP4' => __ ('International Business Mail (L) Country Sort Priority'),
						'DP6' => __ ('International Business Mail (LL) Country Sort Economy'),
						'DW1' => __ ('International Business Parcels'),
						'FS1' => __ ('Royal Mail 24 Standard/Signed For Large Letter (Flat Rate Service)'),
						'FS2' => __ ('Royal Mail 48 Standard/Signed For Large Letter (Flat Rate Service)'),
						'FS7' => __ ('Royal Mail 24 (Presorted) (LL)'),
						'FS8' => __ ('Royal Mail 48 (Presorted) (LL)'),
						'HVB' => __ ('International Tracked Parcels 0-30kg'),
						'HVC' => __ ('International Tracked & Signed Parcels 0-30kg'),
						'HVE' => __ ('International Tracked Parcels 0-30kg Extra Comp'),
						'HVF' => __ ('International Tracked & Signed Parcels 0-30kg Extra Comp'),
						'IE1' => __ ('International Business Parcels Zone Sort Priority Service'),
						'IE3' => __ ('International Business Parcels Zone Sort Economy Service'),
						'IG1' => __ ('International Business Mail Large Letter Zone Sort Priority'),
						'IG3' => __ ('International Business Mail Large Letter Zone Sort Economy'),
						'IG4' => __ ('International Business Mail Large Letter Zone Sort Priority Machine'),
						'IG6' => __ ('International Business Mail Large Letter Zone Sort Economy Machine'),
						'IP1' => __ ('International Business Mail Letters Zone Sort Priority'),
						'IP3' => __ ('International Business Mail Letters Zone Sort Economy'),
						'IP4' => __ ('International Business Mail Letters Zone Sort Priority Machine'),
						'IP6' => __ ('International Business Mail Letters Zone Sort Economy Machine'),
						'ITA' => __ ('Import DE Tracked Returns 24'),
						'ITB' => __ ('Import DE Tracked Returns 48'),
						'ITC' => __ ('Import DE Tracked 24 Letter-boxable High Volume'),
						'ITD' => __ ('Import DE Tracked 48 Letter-boxable High Volume'),
						'ITE' => __ ('Import DE Tracked 48 Letter-boxable'),
						'ITF' => __ ('Import DE Tracked 24 Letter-boxable'),
						'ITL' => __ ('Import DE Tracked 48 High Volume'),
						'ITM' => __ ('Import DE Tracked 24 High Volume'),
						'ITN' => __ ('Import DE Tracked 24'),
						'ITR' => __ ('DE Import to EU Signed Parcel'),
						'ITS' => __ ('Import DE Tracked 48'),
						'MB1' => __ ('International Business Parcels Print Direct Priority'),
						'MB2' => __ ('International Business Parcels Print Direct Standard'),
						'MB3' => __ ('International Business Parcels Print Direct Economy'),
						'MP0' => __ ('International Business Parcels Signed Extra Compensation Country Priced'),
						'MP1' => __ ('International Business Parcels Tracked Zone Sort'),
						'MP4' => __ ('International Business Parcels Tracked Extra Comp Zone Sort'),
						'MP5' => __ ('International Business Parcels Signed  Zone Sort'),
						'MP6' => __ ('International Business Parcels Signed Extra Compensation  Zone Sort'),
						'MP7' => __ ('International Business Parcels Tracked Country Priced'),
						'MP8' => __ ('International Business Parcels Tracked Extra Comp Country Priced'),
						'MP9' => __ ('International Business Parcels Signed Country Priced'),
						'MPL' => __ ('International Business Mail Tracked High Vol. Country Priced'),
						'MPM' => __ ('International Business Mail Tracked & Signed High Vol. Country Priced'),
						'MPN' => __ ('International Business Mail Signed High Vol. Country Priced'),
						'MPO' => __ ('International Business Mail Tracked High Vol. Extra Comp Country Priced'),
						'MPP' => __ ('International Business Mail Tracked & Signed High Vol. Extra Comp Country Priced'),
						'MPR' => __ ('International Business Parcel Tracked Boxable Country Priced'),
						'MTA' => __ ('International Business Parcels Tracked & Signed Zone Sort'),
						'MTB' => __ ('International Business Parcels Tracked & Signed Extra Compensation Zone Sort'),
						'MTC' => __ ('International Business Mail Tracked & Signed Zone Sort'),
						'MTD' => __ ('International Business Mail Tracked & Signed Extra Compensation Zone Sort'),
						'MTE' => __ ('International Business Parcels Tracked & Signed Country Priced'),
						'MTF' => __ ('International Business Parcels Tracked & Signed Extra Compensation Country Priced'),
						'MTG' => __ ('International Business Mail Tracked & Signed Country Priced'),
						'MTI' => __ ('International Business Mail Tracked Zone Sort'),
						'MTJ' => __ ('International Business Mail Tracked Extra Comp Zone Sort'),
						'MTK' => __ ('International Business Mail Tracked Country Priced'),
						'MTM' => __ ('International Business Mail Signed Zone Sort'),
						'MTN' => __ ('International Business Mail Signed Extra Compensation Zone Sort'),
						'MTO' => __ ('International Business Mail Signed Country Priced'),
						'MTP' => __ ('International Business Mail Signed Extra Compensation Country Priced'),
						'MTS' => __ ('International Business Parcels Tracked Direct Ireland Country'),
						'OLA' => __ ('International Standard On Account'),
						'OLS' => __ ('International Economy On Account'),
						'OSA' => __ ('International Signed On Account'),
						'OSB' => __ ('International Signed On Account Extra Comp'),
						'OTA' => __ ('International Tracked On Account'),
						'OTB' => __ ('International Tracked On Account Extra Comp'),
						'OTC' => __ ('International Tracked & Signed On Account'),
						'OTD' => __ ('International Tracked & Signed On Account Extra Comp'),
						'OZ1' => __ ('International Business Mail Mixed Zone Sort Priority'),
						'OZ3' => __ ('International Business Mail Mixed Zone Sort Economy'),
						'OZ4' => __ ('International Business Mail Mixed Zone Sort Priority Machine'),
						'OZ6' => __ ('International Business Mail Mixed Zone Sort Economy Machine'),
						'PK0' => __ ('Royal Mail 48 (LL) Flat Rate'),
						'PK1' => __ ('Royal Mail 24 Standard/Signed For (Parcel - Sort8 - Flat Rate Service)'),
						'PK2' => __ ('Royal Mail 48 Standard/Signed For (Parcel - Sort8 - Flat Rate Service)'),
						'PK3' => __ ('Royal Mail 24 Standard/Signed For (Parcel - Sort8 - Daily Rate Service)'),
						'PK4' => __ ('Royal Mail 48 Standard/Signed For (Parcel - Sort8 - Daily Rate Service)'),
						'PK7' => __ ('Royal Mail 24 (Presorted) (P)'),
						'PK8' => __ ('Royal Mail 48 (Presorted) (P)'),
						'PK9' => __ ('Royal Mail 24 (LL) Flat Rate'),
						'PKB' => __ ('RM24 (Presorted) (P) Annual Flat Rate'),
						'PKD' => __ ('RM48 (Presorted) (P) Annual Flat Rate'),
						'PKK' => __ ('RM48 (Presorted) (LL) Annual Flat Rate'),
						'PKM' => __ ('RM24 (Presorted) (LL) Annual Flat Rate'),
						'PPF1' => __ ('Royal Mail 24 Standard/Signed For (Packetpost- Flat Rate Service)'),
						'PPF2' => __ ('Royal Mail 48 Standard/Signed For (Packetpost- Flat Rate Service)'),
						'PPJ1' => __ ('Parcelpost Flat Rate (Annual)'),
						'PPJ2' => __ ('Parcelpost Flat Rate (Annual)'),
						'PPS' => __ ('RM24 (LL) Annual Flat Rate'),
						'PPT' => __ ('RM48 (LL) Annual Flat Rate'),
						'PS5' => __ ('International Business Personal Correspondence Max Sort (L)'),
						'PS7' => __ ('International Business Mail Large Letter Max Sort Priority Service'),
						'PS8' => __ ('International Business Mail Large Letter Max Sort Economy Service'),
						'PSA' => __ ('International Business Mail Letters Max Sort Standard'),
						'PSB' => __ ('International Business Mail Large Letter Max Sort Standard Service'),
						'RM0' => __ ('Royal Mail 48 (Sort8)(P) Annual Flat Rate'),
						'RM1' => __ ('Royal Mail 24 (LL) Daily Rate'),
						'RM2' => __ ('Royal Mail 24 (P) Daily Rate'),
						'RM3' => __ ('Royal Mail 48 (LL) Daily Rate'),
						'RM4' => __ ('Royal Mail 48 (P) Daily Rate'),
						'RM5' => __ ('Royal Mail 24 (P) Flat Rate'),
						'RM6' => __ ('Royal Mail 48 (P) Flat Rate'),
						'RM7' => __ ('Royal Mail 24 (SORT8) (LL) Annual Flat Rate'),
						'RM8' => __ ('Royal Mail 24 (SORT8) (P) Annual Flat Rate'),
						'RM9' => __ ('Royal Mail 48 (SORT8) (LL) Annual Flat Rate'),
						'SD1' => __ ('Special Delivery Guaranteed By 1PM (£750)'),
						'SD2' => __ ('Special Delivery Guaranteed By 1PM (£1000)'),
						'SD3' => __ ('Special Delivery Guaranteed By 1PM (£2500)'),
						'SD4' => __ ('Special Delivery Guaranteed By 9AM (£750)'),
						'SD5' => __ ('Special Delivery Guaranteed By 9AM (£1000)'),
						'SD6' => __ ('Special Delivery Guaranteed By 9AM (£2500)'),
						'SDA' => __ ('Special Delivery Guaranteed By 1PM (ID) (£750)'),
						'SDB' => __ ('Special Delivery Guaranteed By 1PM (ID) (£1000)'),
						'SDC' => __ ('Special Delivery Guaranteed By 1PM (ID) (£2500)'),
						'SDE' => __ ('Special Delivery Guaranteed By 9AM (ID) (£750)'),
						'SDF' => __ ('Special Delivery Guaranteed By 9AM (ID) (£1000)'),
						'SDG' => __ ('Special Delivery Guaranteed By 9AM (ID) (£2500)'),
						'SDH' => __ ('Special Delivery Guaranteed By 1PM (AGE) (£750)'),
						'SDJ' => __ ('Special Delivery Guaranteed By 1PM (AGE) (£1000)'),
						'SDK' => __ ('Special Delivery Guaranteed By 1PM (AGE) (£2500)'),
						'SDM' => __ ('Special Delivery Guaranteed By 9AM (AGE) (£750)'),
						'SDN' => __ ('Special Delivery Guaranteed By 9AM (AGE) (£1000)'),
						'SDQ' => __ ('Special Delivery Guaranteed By 9AM (AGE) (£2500)'),
						'SDV' => __ ('Special Delivery Guaranteed (AGE) (£750)'),
						'SDW' => __ ('Special Delivery Guaranteed (AGE) (£1000)'),
						'SDX' => __ ('Special Delivery Guaranteed (AGE) (£2500)'),
						'SDY' => __ ('Special Delivery Guaranteed (ID) (£750)'),
						'SDZ' => __ ('Special Delivery Guaranteed (ID) (£1000)'),
						'SEA' => __ ('Special Delivery Guaranteed (ID) (£2500)'),
						'SEB' => __ ('Special Delivery Guaranteed (£750)'),
						'SEC' => __ ('Special Delivery Guaranteed (£1000)'),
						'SED' => __ ('Special Delivery Guaranteed (£2500)'),
						'STL1' => __ ('Royal Mail 1st Class Standard/Signed For (Letters - Daily Rate service)'),
						'STL2' => __ ('Royal Mail 2nd Class Standard/Signed For (Letters - Daily Rate service)'),
						'TPA' => __ ('Tracked 24 High Volume Signature (AGE)'),
						'TPB' => __ ('Tracked 48 High Volume Signature (AGE)'),
						'TPC' => __ ('Tracked 24 Signature (AGE)'),
						'TPD' => __ ('Tracked 48 Signature (AGE)'),
						'TPL' => __ ('Tracked 48 High Volume Signature / No Signature'),
						'TPM' => __ ('Tracked 24 High Volume Signature / No Signature'),
						'TPN' => __ ('Tracked 24 Signature / No Signature'),
						'TPS' => __ ('Tracked 48 Signature / No Signature'),
						'TRL' => __ ('Tracked Letter-Boxable 48 High Volume Signature / No Signature'),
						'TRM' => __ ('Tracked Letter-Boxable 24 High Volume Signature / No Signature'),
						'TRN' => __ ('Tracked Letter-Boxable 24 Signature / No Signature'),
						'TRS' => __ ('Tracked Letter-Boxable 48 Signature / No Signature'),
						'TSN' => __ ('Tracked Returns 24'),
						'TSS' => __ ('Tracked Returns 48'),
						'WE1' => __ ('International Business Parcels Zero Sort Priority'),
						'WE3' => __ ('International Business Parcels Zero Sort Economy'),
						'WG1' => __ ('International Business Mail Large Letter Zero Sort Priority'),
						'WG3' => __ ('International Business Mail Large Letter Zero Sort Economy'),
						'WG4' => __ ('International Business Mail Large Letter Zero Sort Priority Machine'),
						'WG6' => __ ('International Business Mail Large Letter Zero Sort Economy Machine'),
						'WP1' => __ ('International Business Mail Letters Zero Sort Priority'),
						'WP3' => __ ('International Business Mail Letters Zero Sort Economy'),
						'WP4' => __ ('International Business Mail Letters Zero Sort Priority Machine'),
						'WW1' => __ ('International Business Mail Mixed Zero Sort Priority'),
						'WW3' => __ ('International Business Mail Mixed Zero Sort Economy'),
						'WW4' => __ ('International Business Mail Mixed Zero Sort Priority Machine'),
						'Y64' => __ ('Relay Next Day Mail A2'),
						'Y65' => __ ('Relay Next Day Mail A3'),
						'Y66' => __ ('Relay Next Day Sack'),
						'Y67' => __ ('Relay Next Day Tote'),
						'Y68' => __ ('Relay Next Day Retail'),
						'Y69' => __ ('Relay Next Day Tube'),
						'Y70' => __ ('Relay Next Day Clearings'),
						'Y71' => __ ('Relay Next Day Archives'),
						'Y72' => __ ('Relay Next Day Parcel'),
						'Y73' => __ ('Relay Next Day Special Returns'),
						'Y74' => __ ('Relay Next Day Parts'),
						'Y75' => __ ('Relay Next Day Fragile'),
						'Y76' => __ ('Relay Next Day Mail'),
						'Y77' => __ ('Relay Next Day Stationary'),
						'Y78' => __ ('Relay Next Day Returns'),
						'Y79' => __ ('Relay Next Day Uniform'),
						'Y80' => __ ('Relay Next Day Sensitive Waste (SDS)'),
						'Y81' => __ ('Relay Next Day Enhanced 500'),
						'Y82' => __ ('Relay Next Day Enhanced 1000'),
						'Y83' => __ ('Relay Next Day Enhanced 1500'),
						'Y84' => __ ('Relay Next Day Enhanced 2000'),
						'Y85' => __ ('Relay Next Day Enhanced 2500'),
						'Y86' => __ ('Relay Next Day Enhanced 3000'),
						'Y87' => __ ('Relay Next Day Box'),
						'Y88' => __ ('Relay Next Day Recycle'),
						'Y89' => __ ('Relay Next Day Pallet'),
						'Y90' => __ ('Relay Next Day Loose'),
						'Y91' => __ ('Relay Next Day Pouch'),
						'Y92' => __ ('Relay Next Day Holdall'),
						'Y93' => __ ('Relay Next Day Clearings Pouch'),
						'Y94' => __ ('Relay Next Day HO Mail Pouch'),
						'Y95' => __ ('Relay Next Day Returns Pouch'),
						'Y96' => __ ('Relay Next Day Archive Pouch'),
						'Y97' => __ ('Relay Next Day Critical Run Pouch'),
						'Y98' => __ ('Relay Next Day Smart Meter Tote'),
						'Y99' => __ ('Relay Next Day Mail A4'),
            ),
            'shipment_type' => array(
                'letter' => __('Letter'),
                'large_letter' => __('Large Letter'),
                'small_parcel' => __('Small Parcel'),
                'medium_parcel' => __('Medium Parcel'),
            ),
            'international_searvices' => array(
                'BG1' => __ ('International Business Personal Correspondence Max Sort Residue (LL)'),
				'BG2' => __ ('International Business Mail (LL) Max Sort Residue Standard'),
				'BG3' => __ ('International Business Mail (LL) Max Sort Residue Economy'),
				'BP1' => __ ('International Business Personal Correspondence Max Sort Residue (L)'),
				'BP2' => __ ('International Business Mail (L) Max Sort Residue Standard'),
				'BP3' => __ ('International Business Mail (L) Max Sort Residue Economy'),
				'BPI' => __ ('International Business Printed Matter Packet'),
				'DE1' => __ ('International Business Parcels Zero Sort High Vol Priority'),
				'DE4' => __ ('International Business Parcels Zero Sort Priority'),
				'DE6' => __ ('International Business Parcels Zero Sort Priority'),
				'DG1' => __ ('International Business Mail (LL) Country Priced High Vol Priority'),
				'DG3' => __ ('International Business Mail (LL) Country Priced High Vol Economy'),
				'DG4' => __ ('International Business Mail (LL) Country Priced Priority'),
				'DG6' => __ ('International Business Mail (LL) Country Priced Economy'),
				'DP1' => __ ('International Business Mail (L) Country Sort High Vol Priority'),
				'DP3' => __ ('International Business Personal Correspondence (L) Untracked'),
				'DP4' => __ ('International Business Mail (L) Country Sort Priority'),
				'DP6' => __ ('International Business Mail (LL) Country Sort Economy'),
				'DW1' => __ ('International Business Parcels'),
				'HVB' => __ ('International Tracked Parcels 0-30kg'),
				'HVC' => __ ('International Tracked & Signed Parcels 0-30kg'),
				'HVE' => __ ('International Tracked Parcels 0-30kg Extra Comp'),
				'HVF' => __ ('International Tracked & Signed Parcels 0-30kg Extra Comp'),
				'IE1' => __ ('International Business Parcels Zone Sort Priority Service'),
				'IE3' => __ ('International Business Parcels Zone Sort Economy Service'),
				'IG1' => __ ('International Business Mail Large Letter Zone Sort Priority'),
				'IG3' => __ ('International Business Mail Large Letter Zone Sort Economy'),
				'IG4' => __ ('International Business Mail Large Letter Zone Sort Priority Machine'),
				'IG6' => __ ('International Business Mail Large Letter Zone Sort Economy Machine'),
				'IP1' => __ ('International Business Mail Letters Zone Sort Priority'),
				'IP3' => __ ('International Business Mail Letters Zone Sort Economy'),
				'IP4' => __ ('International Business Mail Letters Zone Sort Priority Machine'),
				'IP6' => __ ('International Business Mail Letters Zone Sort Economy Machine'),
				'MB1' => __ ('International Business Parcels Print Direct Priority'),
				'MB2' => __ ('International Business Parcels Print Direct Standard'),
				'MB3' => __ ('International Business Parcels Print Direct Economy'),
				'MP0' => __ ('International Business Parcels Signed Extra Compensation Country Priced'),
				'MP1' => __ ('International Business Parcels Tracked Zone Sort'),
				'MP4' => __ ('International Business Parcels Tracked Extra Comp Zone Sort'),
				'MP5' => __ ('International Business Parcels Signed  Zone Sort'),
				'MP6' => __ ('International Business Parcels Signed Extra Compensation  Zone Sort'),
				'MP7' => __ ('International Business Parcels Tracked Country Priced'),
				'MP8' => __ ('International Business Parcels Tracked Extra Comp Country Priced'),
				'MP9' => __ ('International Business Parcels Signed Country Priced'),
				'MPL' => __ ('International Business Mail Tracked High Vol. Country Priced'),
				'MPM' => __ ('International Business Mail Tracked & Signed High Vol. Country Priced'),
				'MPN' => __ ('International Business Mail Signed High Vol. Country Priced'),
				'MPO' => __ ('International Business Mail Tracked High Vol. Extra Comp Country Priced'),
				'MPP' => __ ('International Business Mail Tracked & Signed High Vol. Extra Comp Country Priced'),
				'MPR' => __ ('International Business Parcel Tracked Boxable Country Priced'),
				'MTA' => __ ('International Business Parcels Tracked & Signed Zone Sort'),
				'MTB' => __ ('International Business Parcels Tracked & Signed Extra Compensation Zone Sort'),
				'MTC' => __ ('International Business Mail Tracked & Signed Zone Sort'),
				'MTD' => __ ('International Business Mail Tracked & Signed Extra Compensation Zone Sort'),
				'MTE' => __ ('International Business Parcels Tracked & Signed Country Priced'),
				'MTF' => __ ('International Business Parcels Tracked & Signed Extra Compensation Country Priced'),
				'MTG' => __ ('International Business Mail Tracked & Signed Country Priced'),
				'MTI' => __ ('International Business Mail Tracked Zone Sort'),
				'MTJ' => __ ('International Business Mail Tracked Extra Comp Zone Sort'),
				'MTK' => __ ('International Business Mail Tracked Country Priced'),
				'MTM' => __ ('International Business Mail Signed Zone Sort'),
				'MTN' => __ ('International Business Mail Signed Extra Compensation Zone Sort'),
				'MTO' => __ ('International Business Mail Signed Country Priced'),
				'MTP' => __ ('International Business Mail Signed Extra Compensation Country Priced'),
				'MTS' => __ ('International Business Parcels Tracked Direct Ireland Country'),
				'OLA' => __ ('International Standard On Account'),
				'OLS' => __ ('International Economy On Account'),
				'OSA' => __ ('International Signed On Account'),
				'OSB' => __ ('International Signed On Account Extra Comp'),
				'OTA' => __ ('International Tracked On Account'),
				'OTB' => __ ('International Tracked On Account Extra Comp'),
				'OTC' => __ ('International Tracked & Signed On Account'),
				'OTD' => __ ('International Tracked & Signed On Account Extra Comp'),
				'OZ1' => __ ('International Business Mail Mixed Zone Sort Priority'),
				'OZ3' => __ ('International Business Mail Mixed Zone Sort Economy'),
				'OZ4' => __ ('International Business Mail Mixed Zone Sort Priority Machine'),
				'OZ6' => __ ('International Business Mail Mixed Zone Sort Economy Machine'),
				'PS5' => __ ('International Business Personal Correspondence Max Sort (L)'),
				'PS7' => __ ('International Business Mail Large Letter Max Sort Priority Service'),
				'PS8' => __ ('International Business Mail Large Letter Max Sort Economy Service'),
				'PSA' => __ ('International Business Mail Letters Max Sort Standard'),
				'PSB' => __ ('International Business Mail Large Letter Max Sort Standard Service'),
				'WE1' => __ ('International Business Parcels Zero Sort Priority'),
				'WE3' => __ ('International Business Parcels Zero Sort Economy'),
				'WG1' => __ ('International Business Mail Large Letter Zero Sort Priority'),
				'WG3' => __ ('International Business Mail Large Letter Zero Sort Economy'),
				'WG4' => __ ('International Business Mail Large Letter Zero Sort Priority Machine'),
				'WG6' => __ ('International Business Mail Large Letter Zero Sort Economy Machine'),
				'WP1' => __ ('International Business Mail Letters Zero Sort Priority'),
				'WP3' => __ ('International Business Mail Letters Zero Sort Economy'),
				'WP4' => __ ('International Business Mail Letters Zero Sort Priority Machine'),
				'WW1' => __ ('International Business Mail Mixed Zero Sort Priority'),
				'WW3' => __ ('International Business Mail Mixed Zero Sort Economy'),
				'WW4' => __ ('International Business Mail Mixed Zero Sort Priority Machine'),

            ),
            'container' => array(
                'F' => '00', // Inland Large Letter
                'L' => '01', // Inland Letter
                'N' => '02', // Inland format Not Applicable
                'P' => '03', // Inland Parcel
                'I_E' => '20', // International Parcel
                'I_G' => '21', // International Large Letter
                'I_N' => '22', // International Format Not Applicable
                'I_P' => '23', // International Letter
            ),
            'container_description' => array(
                'F' => __('Inland Large Letter'),
                'L' => __('Inland Letter'),
                'N' => __('Inland format Not Applicable'),
                'P' => __('Inland Parcel'),
                'I_E' => __('International Parcel'),
                'I_G' => __('International Large Letter'),
                'I_N' => __('International Format Not Applicable'),
                'I_P' => __('International Letter'),
            ),
            'bfpo_service_format' => array(
                '1' => __('International Flat'),
                '2' => __('International Letter'),
                '3' => __('International Pack'),
            ),
            'bfpo_format' => array(
                'EAA' => __('SD 0 - 100G £500 COMP'),
                'EAB' => __('SD 101 - 500G £500 COMP'),
                'EAC' => __('SD 501- 1KG £500 COMP'),
                'EAD' => __('SD 1001G - 2KG £500 COMP'),
                'EBA' => __('SD 0 - 100G £1000 COMP'),
                'EBB' => __('SD 101 - 500G £1000 COMP'),
                'EBC' => __('SD 501- 1KG £1000 COMP'),
                'EBD' => __('SD 1001G - 2KG £1000 COMP'),
                'ECA' => __('SD 0 - 100G £2500 COMP'),
                'ECC' => __('SD 501- 1KG £2500 COMP'),
                'ECD' => __('SD 1001G - 2KG £2500 COMP'),
                'EVB' => __('SD 101 - 500G £2500 COMP'),
                'FAE' => __('FORCES AEROGRAMMES'),
            ),
            'enhancement_type' => array(
                '1' => __('Consequential Loss £1000'),
                '2' => __('Consequential Loss £2500'),
                '3' => __('Consequential Loss £5000'),
                '4' => __('Consequential Loss £7500'),
                '5' => __('Consequential Loss £10000'),
                '6' => __('Recorded'),
                '11' => __('Consequential Loss £750'),
                '12' => __('Tracked Signature'),
                '13' => __('SMS Notification'),
                '14' => __('E-Mail Notification'),
//                '15' => __('Safeplace'),
                '16' => __('SMS & E-Mail Notification'),
                '22' => __('Local Collect'),
                '24' => __('Saturday Guaranteed'),
            ),
            'enhancement_type_group' => array(
                '1' => array('1', '2', '3', '4', '5', '11'),
                '2' => array('6'),
                '3' => array('12', /* '15' */),
                '4' => array('13', '14', '16'),
                '5' => array('22'),
                '6' => array('24'),
            ),
            'enhancement_group_description' => array(
                '1' => __('Consequential Loss Insurance'),
                '2' => __('Recorded Signed For Mail'),
                '3' => __('Tracked Delivery Options'),
                '4' => __('Tracking Notifications'),
                '5' => __('Local Collect'),
                '6' => __('Saturday Guaranteed'),
            ),
            'condition_name' => array(
                'package_weight' => __('Weight vs. Destination(system weight unit)'),
                'package_value' => __('Price vs. Destination'),
                'package_qty' => __('# of Items vs. Destination'),
            ),
            'condition_name_short' => array(
                'package_weight' => __('Weight (and above)'),
                'package_value' => __('Order Subtotal (and above)'),
                'package_qty' => __('# of Items (and above)'),
            ),
            'unit_of_measure' => array(
                \Magento\Framework\Measure\Weight::POUND => __('POUND'),
                \Magento\Framework\Measure\Weight::KILOGRAM => __('KILOGRAM'),
            ),
            'errors' => array(
                'E0000' => __('Internal Exception Occurred. Please contact to the developer if occurred again.'),
                'E0001' => __('Service Unavailable. Please contact to the developer if occurred again.'),
                'E0002' => __('Service Temporarily Unavailable. Please try again later.'),
                'E0004' => __('Failed Schema Validation. Please contact to the developer if occurred again.'),
                'E0007' => __('Authorisation Failure. Please make sure Royal Mail API credentials are correct.'),
                'E0010' => __('Configured Throttling Rate for Service Exceeded. Please try again later.'),
            )
        );
    }

    /**
     * Returns code data
     * @param type $type
     * @param type $code
     * @return boolean
     */
    public function getCode($type, $code = '')
    {
        if (!isset($this->_codes[$type])) {
            return false;
        } elseif ('' === $code) {
            return $this->_codes[$type];
        }

        if (!isset($this->_codes[$type][$code])) {
            return false;
        } else {
            return $this->_codes[$type][$code];
        }
    }

}
